import "./globals.css";
import Header from "@/app/components/Header/Header";

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className={'container'}>
          <Header/>
          <div className={'px-6'}>
              {children}
          </div>
        </main>
      </body>
    </html>
  );
}
